---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  dependsOn:
    - name: charts
    - name: infrastructure
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/homelab
  prune: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secret-vars
