---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: whoami-letsencrypt-production-cert
  namespace: cert-manager
spec:
  commonName: whoami.${SECRET_INTERNAL_DOMAIN_NAME}
  dnsNames:
    - whoami.${SECRET_INTERNAL_DOMAIN_NAME}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: whoami-tls
