---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: ${SECRET_LETS_ENCRYPT_EMAIL}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production-account-key
    solvers:
    - dns01:
       route53:
         region: ${SECRET_AWS_REGION}
         accessKeyID: ${SECRET_AWS_ACCESS_KEY_ID}
         secretAccessKeySecretRef:
           name: cluster-secret-vars
           key: ${SECRET_AWS_ACCESS_KEY}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: ${SECRET_LETS_ENCRYPT_EMAIL}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
    - dns01:
       route53:
         region: ${SECRET_AWS_REGION}
         accessKeyID: ${SECRET_AWS_ACCESS_KEY_ID}
         secretAccessKeySecretRef:
           name: cluster-secret-vars
           key: ${SECRET_AWS_ACCESS_KEY}
