---
apiVersion: v1
kind: ConfigMap
metadata:
  name: focalboard-config-map
  namespace: focalboard
data:
  config.json: |+
    {
      "serverRoot": "http://localhost:8000",
      "port": 8000,
      "dbtype": "postgres",
      "dbconfig": "postgres://${FOCALBOARD_DB_USER}:${FOCALBOARD_DB_PASS}@${FOCALBOARD_DB_HOST}.${SECRET_INTERNAL_DOMAIN_NAME}:5432/${FOCALBOARD_DB_NAME}?sslmode=verify-full&connect_timeout=10",
      "useSSL": false,
      "webpath": "./pack",
      "filespath": "/data/files",
      "telemetry": true,
      "session_expire_time": 2592000,
      "session_refresh_time": 18000,
      "localOnly": false,
      "enableLocalMode": true,
      "localModeSocketLocation": "/var/tmp/focalboard_local.socket"
    }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: focalboard-data-pvc
  namespace: focalboard
  annotations:
    volumeType: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: local-path-customized
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: focalboard-deployment
  namespace: focalboard
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: focalboard
  template:
    metadata:
      labels:
        app: focalboard
    spec:
      containers:
        - name: focalboard
          image: mattermost/focalboard:7.9.3
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: config
              mountPath: /opt/focalboard/config.json
              subPath: config.json
              readOnly: true
            - name: data
              mountPath: /data
      volumes:
        - name: config
          configMap:
            name: focalboard-config-map
        - name: data
          persistentVolumeClaim:
            claimName: focalboard-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: focalboard-service
  namespace: focalboard
spec:
  type: ClusterIP
  ports:
    - name: http
      targetPort: 8000
      port: 8000
      protocol: TCP
  selector:
    app: focalboard
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: focalboard-ingress
  namespace: focalboard
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
    - host: focalboard.${SECRET_INTERNAL_DOMAIN_NAME}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: focalboard-service
                port:
                  number: 8000
  tls:
    - hosts:
        - focalboard.${SECRET_INTERNAL_DOMAIN_NAME}
      secretName: focalboard-tls
