---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-backup-script
  namespace: manyfold
data:
  backup.sh: |
    #!/bin/sh
    set -e

    BACKUP_DIR="/backups"
    BACKUP_FILE="$${BACKUP_DIR}/postgres_$${APP_NAME}_$$(date +%Y%m%d_%H%M).sql.gz"

    echo "$$(date +%Y%m%d_%H%M) - INFO: Starting backup of $${DATABASE_NAME}"
    pg_dump -h "$${DATABASE_HOST}" -U "$${PGUSER}" -d "$${DATABASE_NAME}" | gzip > "$${BACKUP_FILE}"

    if [ -f "$${BACKUP_FILE}" ]; then
      BACKUP_SIZE=$$(du -h "$${BACKUP_FILE}" | cut -f1)
      echo "$$(date +%Y%m%d_%H%M) - INFO: Backup completed successfully: $${BACKUP_FILE} ($${BACKUP_SIZE})"
    else
      echo "$$(date +%Y%m%d_%H%M) - ERROR: Backup file was not created"
      exit 1
    fi

    echo "$$(date +%Y%m%d_%H%M) - INFO: Backup process completed"
