---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: manyfold-postgres
  namespace: manyfold
# https://cloudnative-pg.io/documentation/1.28/cloudnative-pg.v1/#postgresql-cnpg-io-v1-ClusterSpec
spec:
  instances: 1
  # https://github.com/cloudnative-pg/postgres-containers
  imageName: ghcr.io/cloudnative-pg/postgresql:17.7-minimal-trixie@sha256:3546b262c7e773012ab181dd71c4593fab1a36ec1c4ca5d9b111aafff249c8cb
  storage:
    size: 1Gi
    storageClass: local-path-customized
  postgresql:
  bootstrap:
    initdb:
      database: manyfold
      owner: manyfold
      secret:
        name: manyfold-postgres
