---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: manyfold-postgres
  namespace: manyfold
# https://cloudnative-pg.io/documentation/1.28/cloudnative-pg.v1/#postgresql-cnpg-io-v1-ClusterSpec
spec:
  instances: 1
  # https://github.com/cloudnative-pg/postgres-containers
  imageName: ghcr.io/cloudnative-pg/postgresql:17.9-minimal-trixie@sha256:c31dadb03987ad6e8b0b8148b2a3168c90ad11862bba7344f3859edd7062ddef
  storage:
    size: 1Gi
    storageClass: local-path-customized
  postgresql:
  bootstrap:
    initdb:
      database: manyfold
      owner: manyfold
      secret:
        name: manyfold-postgres
