---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: manyfold-postgres
  namespace: manyfold
# https://cloudnative-pg.io/documentation/1.28/cloudnative-pg.v1/#postgresql-cnpg-io-v1-ClusterSpec
spec:
  instances: 1
  # https://github.com/cloudnative-pg/postgres-containers
  imageName: ghcr.io/cloudnative-pg/postgresql:18.1-minimal-trixie@sha256:140e2ab67b43966c35bf687a910fb1aee1678bc61283acd624575b1a01ea9063
  storage:
    size: 1Gi
    storageClass: local-path-customized
  postgresql:
  bootstrap:
    initdb:
      database: manyfold
      owner: manyfold
      secret:
        name: manyfold-postgres
