---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: manyfold-postgres
  namespace: manyfold
# https://cloudnative-pg.io/documentation/1.28/cloudnative-pg.v1/#postgresql-cnpg-io-v1-ClusterSpec
spec:
  instances: 1
  # https://github.com/cloudnative-pg/postgres-containers
  imageName: ghcr.io/cloudnative-pg/postgresql:17.9-minimal-trixie@sha256:945021c544177c461162ccbc64a354625d6e88c2aa754bd601584a13fa2a94ab
  storage:
    size: 1Gi
    storageClass: local-path-customized
  postgresql:
  bootstrap:
    initdb:
      database: manyfold
      owner: manyfold
      secret:
        name: manyfold-postgres
