---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manyfold-data-pvc
  namespace: manyfold
  annotations:
    volumeType: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path-customized
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manyfold
  namespace: manyfold
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: manyfold
  template:
    metadata:
      labels:
        app: manyfold
    spec:
      containers:
        - name: manyfold
          image: ghcr.io/manyfold3d/manyfold:0.129.4@sha256:f6a6ce77d12914e6ddbdd8a5457dc41f8f6445ff802cd1a486064b1b82da0746
          ports:
            - containerPort: 3214
          env:
            - name: DATABASE_ADAPTER
              value: "postgresql"
            - name: DATABASE_HOST
              value: "manyfold-postgres-rw.manyfold.svc.cluster.local"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              value: "manyfold"
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: manyfold-postgres
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: manyfold-postgres
                  key: password
            - name: DEMO_MODE
              value: "false"
            - name: REDIS_URL
              value: "redis://valkey.manyfold.svc.cluster.local:6379/1"
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: manyfold
                  key: secretKeyBase
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: manyfold-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: manyfold
  namespace: manyfold
spec:
  type: ClusterIP
  ports:
    - name: http
      targetPort: 3214
      port: 3214
      protocol: TCP
  selector:
    app: manyfold
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: manyfold
  namespace: manyfold
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    cert-manager.io/private-key-algorithm: RSA
    cert-manager.io/private-key-size: 4096
    cert-manager.io/private-key-rotation-policy: Always
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
    - host: manyfold.${SECRET_INTERNAL_DOMAIN_NAME}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: manyfold
                port:
                  number: 3214
  tls:
    - hosts:
        - manyfold.${SECRET_INTERNAL_DOMAIN_NAME}
      secretName: manyfold-tls
