---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey-deployment
  namespace: valkey
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: valkey
  template:
    metadata:
      labels:
        app: valkey
    spec:
      containers:
        - name: valkey
          image: valkey/valkey:9.0.1-alpine@sha256:1be494495248d53e3558b198a1c704e6b559d5e99fe4c926e14a8ad24d76c6fa
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: valkey-service
  namespace: valkey
spec:
  type: ClusterIP
  ports:
    - name: http
      targetPort: 6379
      port: 6379
      protocol: TCP
  selector:
    app: valkey
