---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyberchef-deployment
  namespace: tools
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: cyberchef
  template:
    metadata:
      labels:
        app: cyberchef
    spec:
      containers:
        - name: cyberchef
          image: ghcr.io/gchq/cyberchef:10.16.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cyberchef-service
  namespace: tools
spec:
  type: ClusterIP
  ports:
    - name: http
      targetPort: 80
      port: 80
      protocol: TCP
  selector:
    app: cyberchef
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cyberchef-ingress
  namespace: tools
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
    - host: cyberchef.${SECRET_INTERNAL_DOMAIN_NAME}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cyberchef-service
                port:
                  number: 80
  tls:
    - hosts:
        - cyberchef.${SECRET_INTERNAL_DOMAIN_NAME}
      secretName: cyberchef-tls
