---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spdf-deployment
  namespace: tools
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: spdf
  template:
    metadata:
      labels:
        app: spdf
    spec:
      containers:
        - name: spdf
          image: ghcr.io/stirling-tools/s-pdf:1.5.0@sha256:bfe2b8dd378c4f3d5fc1d2fc7649a357d0916b3a713022aa70ac3f08d6302cbc
          ports:
            - containerPort: 8080
          env:
            - name: SYSTEM_ENABLEANALYTICS
              value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: spdf-service
  namespace: tools
spec:
  type: ClusterIP
  ports:
    - name: http
      targetPort: 8080
      port: 8080
      protocol: TCP
  selector:
    app: spdf
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spdf-ingress
  namespace: tools
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    cert-manager.io/private-key-algorithm: RSA
    cert-manager.io/private-key-size: 4096
    cert-manager.io/private-key-rotation-policy: Always
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
    - host: spdf.${SECRET_INTERNAL_DOMAIN_NAME}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spdf-service
                port:
                  number: 8080
  tls:
    - hosts:
        - spdf.${SECRET_INTERNAL_DOMAIN_NAME}
      secretName: spdf-tls
