---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: portainer
  namespace: portainer
spec:
  interval: 15m
  chart:
    spec:
      chart: portainer
      version: 2.33.0
      sourceRef:
        kind: HelmRepository
        name: portainer-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  # https://portainer.github.io/k8s/charts/portainer/
  values:
    image:
      repository: portainer/portainer-ce
    ingress:
      enabled: false
    persistence:
      enabled: true
      storageClass: local-path-customized
      size: 1Gi
    service:
      type: ClusterIP
