---
# Creating a custom StorageClass so that I can set some settings at the bottom
# https://github.com/rancher/local-path-provisioner/issues/194
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-customized
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
# https://kubernetes.io/docs/tasks/administer-cluster/change-pv-reclaim-policy/
reclaimPolicy: Retain
# https://github.com/rancher/local-path-provisioner/issues/107
# allowVolumeExpansion makes no difference since storage is backed by the node
allowVolumeExpansion: true
