---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system-helm-repositories
  namespace: flux-system
spec:
  interval: 1m
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./cluster/homelab/flux-system/helm-repositories
  prune: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secret-vars
