---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: reloader
spec:
  interval: 15m
  chart:
    spec:
      chart: reloader
      version: 2.2.7
      sourceRef:
        kind: HelmRepository
        name: stakater-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  # https://github.com/stakater/Reloader/blob/master/deployments/kubernetes/chart/reloader/values.yaml
  values:
    reloader:
      reloadStrategy: annotations
