---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geoipupdate-data-pvc
  namespace: graylog
  annotations:
    volumeType: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: local-path-customized
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: geoipupdate-deployment
  namespace: graylog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geoipupdate
  template:
    metadata:
      labels:
        app: geoipupdate
    spec:
      containers:
        - name: geoipupdate
          image: maxmindinc/geoipupdate:v4.10.0
          env:
            - name: GEOIPUPDATE_EDITION_IDS
              value: 'GeoLite2-ASN GeoLite2-City GeoLite2-Country'
            - name: GEOIPUPDATE_FREQUENCY
              value: 72
            - name: GEOIPUPDATE_ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  name: graylog-secret-vars
                  key: GEOIPUPDATE_ACCOUNT_ID
            - name: GEOIPUPDATE_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: graylog-secret-vars
                  key: GEOIPUPDATE_LICENSE_KEY
          volumeMounts:
            - name: data
              mountPath: /usr/share/GeoIP
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: geoipupdate-data-pvc

