---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-backup-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-customized
  local:
    path: /custom/backup/backup/mongo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-backup-pvc
  namespace: flux-system
  annotations:
    volumeType: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path-customized
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodb-backup-cronjob
  namespace: flux-system
spec:
  schedule: "0 8 * * 0"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mongodb-backup
              image: mongo:5.0.17
              command: ["sh", "-c"]
              args: ["mongodump --username ${GRAYLOG_MONGODB_USERNAME} --password ${GRAYLOG_MONGODB_PASSWORD} --authenticationDatabase admin --quiet --gzip --archive=/backup/$(uname -n)_$(date +%Y%m%d_%H%M)_all_mongo_dbs.gz"]
              volumeMounts:
                - name: backup-dir
                  mountPath: /backup/mongo
          restartPolicy: OnFailure
          volumes:
            - name: backup-dir
              persistentVolumeClaim:
                claimName: mongodb-backup-pvc
