---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-backup-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-customized
  local:
    path: /custom/backup/backup/k8s
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodb-backup-cronjob
  namespace: flux-system
spec:
  schedule: "0 8 * * 0"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mongodb-backup
              image: mongo:5.0.17
              command: ["sh", "-c"]
              args: ["mongodump --username ${GRAYLOG_MONGODB_USERNAME} --password ${GRAYLOG_MONGODB_PASSWORD} --authenticationDatabase admin --quiet --gzip --archive=/backup/$(uname -n)_$(date +%Y%m%d_%H%M)_all_mongo_dbs.gz"]
              volumeMounts:
                - name: backup-dir
                  mountPath: /k8s
          restartPolicy: OnFailure
          volumes:
            - name: backup-dir
              local:
                path: /custom/backup/backup/k8s
