---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data-pvc
  namespace: graylog
  annotations:
    volumeType: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path-customized
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data-configdb-pvc
  namespace: graylog
  annotations:
    volumeType: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: local-path-customized
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: graylog
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:5.0.17
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: graylog-secret-vars
                  key: MONGO_INITDB_DATABASE
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: graylog-secret-vars
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: graylog-secret-vars
                  key: MONGO_INITDB_ROOT_PASSWORD
          livenessProbe:
            exec:
              command:
                - mongo
                - --disableImplicitSessions
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - mongo
                - --disableImplicitSessions
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          volumeMounts:
            - name: config
              mountPath: /docker-entrypoint-initdb.d/create-user.js
              subPath: create-user.js
              readOnly: true
            - name: data
              mountPath: /data/db
            - name: data-configdb
              mountPath: /data/configdb
      volumes:
        - name: config
          configMap:
            name: mongodb-config-map
        - name: data
          persistentVolumeClaim:
            claimName: mongodb-data-pvc
        - name: data-configdb
          persistentVolumeClaim:
            claimName: mongodb-data-configdb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: graylog
spec:
  type: ClusterIP
  ports:
    - name: http
      targetPort: 27017
      port: 27017
      protocol: TCP
  selector:
    app: mongodb
