---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config-map
  namespace: graylog
data:
  create-user.js: |+
    db = db.getSiblingDB("${GRAYLOG_MONGODB_DATABASE}");
    db.createUser({
      user: "${GRAYLOG_MONGODB_USERNAME}",
      pwd: "${GRAYLOG_MONGODB_PASSWORD}",
      roles: [ { role: "dbOwner", db: "${GRAYLOG_MONGODB_DATABASE}" } ]
    });
