---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: portainer
  namespace: portainer
spec:
  interval: 15m
  chart:
    spec:
      chart: portainer
      version: 2.16.0
      sourceRef:
        kind: HelmRepository
        name: portainer-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    persistence:
      storageClass: local-path-customized
    service:
      type: ClusterIP
    ingress:
      enabled: "true"
