---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: portainer
  namespace: portainer
spec:
  interval: 15m
  chart:
    spec:
      chart: portainer
      version: 1.0.37
      sourceRef:
        kind: HelmRepository
        name: portainer-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  # https://portainer.github.io/k8s/charts/portainer/
  values:
    #   enterpriseEdition:
    #      enabled: "false"
    image:
      repository: portainer/portainer-ce
      tag: 2.16.1-alpine
    ingress:
      enabled: "false"
    persistence:
      enabled: "true"
      storageClass: local-path-customized
      size: 5Gi
    service:
      type: ClusterIP
