---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 15m
  chart:
    spec:
      chart: prometheus
      version: 27.23.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  # https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml
  values:
    ingress:
      enabled: false
    persistentVolume:
      enabled: true
      storageClass: "local-path-customized"
      size: 8Gi
    service:
      type: ClusterIP
    alertmanager:
      enabled: false
    kube-state-metrics:
      enabled: false
    prometheus-node-exporter:
      enabled: false
    prometheus-pushgateway:
      enabled: false
