---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 15m
  chart:
    spec:
      chart: prometheus
      version: 27.23.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  # https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml
  values:
    server:
      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          cert-manager.io/private-key-algorithm: RSA
          cert-manager.io/private-key-size: 4096
          cert-manager.io/private-key-rotation-policy: Always
          traefik.ingress.kubernetes.io/router.tls: "true"
        hosts:
          - prometheus-k3s.${SECRET_INTERNAL_DOMAIN_NAME}
        tls:
          - secretName: prometheus-k3s-tls
            hosts:
              - prometheus-k3s.${SECRET_INTERNAL_DOMAIN_NAME}
      persistentVolume:
        enabled: true
        storageClass: local-path-customized
        size: 8Gi
      service:
        enabled: true
        type: ClusterIP
    alertmanager:
      enabled: false
    kube-state-metrics:
      enabled: false
    prometheus-node-exporter:
      enabled: false
    prometheus-pushgateway:
      enabled: false
