---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 15m
  chart:
    spec:
      chart: weave-gitops
      version: 4.0.15
      sourceRef:
        kind: HelmRepository
        name: weave-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  # https://docs.gitops.weave.works/docs/references/helm-reference/
  values:
    image:
      repository: ghcr.io/weaveworks/wego-app
    ingress:
      enabled: false
    service:
      create: true
      type: ClusterIP
    securityContext:
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
    adminUser:
      create: true
      createClusterRole: true
      createSecret: false
      username: "admin"
    rbac:
      create: true
      impersonationResources: ["users", "groups"]
