apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: drawio
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: main/homelab/drawio
    repoURL: {{ .Values.spec.repo.url }}
    targetRevision: {{ .Values.spec.repo.revision }}
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
