---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: homebox-postgres-backup
  namespace: homebox
spec:
  schedule: "0 3 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          securityContext:
            # needed to backup the the /custom/backup/backup location on the host
            runAsUser: 0
            runAsGroup: 0
            fsGroup: 0
          containers:
            - name: pg-backup
              image: ghcr.io/cloudnative-pg/postgresql:17.7-minimal-trixie@sha256:dd6f9cda42c24bcd8ee2b619516e2aa5ddc40317c00d55d808543cef51286701
              command:
                - /bin/bash
                - -c
                - |
                  set -e

                  BACKUP_DIR="/backups"
                  BACKUP_FILE="${BACKUP_DIR}/${APP_NAME}-$(date +%Y%m%d_%H%M).sql.gz"

                  # Perform the backup
                  echo "$(date +%Y%m%d_%H%M) - INFO: Starting backup of ${DATABASE_NAME}"
                  pg_dump -h "${DATABASE_HOST}" -U "${PGUSER}" -d "${DATABASE_NAME}" | gzip > "${BACKUP_FILE}"

                  # Verify backup file was created
                  if [ -f "${BACKUP_FILE}" ]; then
                    BACKUP_SIZE=$(du -h "${BACKUP_FILE}" | cut -f1)
                    echo "$(date +%Y%m%d_%H%M) - INFO: Backup completed successfully: ${BACKUP_FILE} (${BACKUP_SIZE})"
                  else
                    echo "$(date +%Y%m%d_%H%M) - ERROR: Backup file was not created"
                    exit 1
                  fi

                  echo "$(date +%Y%m%d_%H%M) - INFO: Backup process completed"
              env:
                ########################################
                # Change these values when copying cronjob
                ########################################
                - name: APP_NAME
                  value: homebox
                - name: DATABASE_HOST
                  value: homebox-postgres-rw
                - name: DATABASE_NAME
                  value: homebox
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      name: homebox-postgres
                      key: username
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: homebox-postgres
                      key: password
              volumeMounts:
                - name: backup-volume
                  mountPath: /backups
          volumes:
            - name: backup-volume
              hostPath:
                # this already exists on the host
                path: /custom/backup/backup
                type: Directory
