---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: homebox-postgres-backup
  namespace: homebox
spec:
  schedule: "0 3 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          securityContext:
            # needed to backup the the /custom/backup/backup location on the host
            runAsUser: 0
            runAsGroup: 0
            fsGroup: 0
          containers:
            - name: pg-backup
              image: ghcr.io/cloudnative-pg/postgresql:17.7-minimal-trixie@sha256:a4e28c646ca492f437b8ba72e1aea5d0dc3e31c54a95750adcb5ddd5c2c8d388
              command: ["/bin/sh", "/scripts/backup.sh"]
              env:
                ########################################
                # Change these values when copying cronjob
                ########################################
                - name: APP_NAME
                  value: homebox
                - name: DATABASE_HOST
                  value: homebox-postgres-rw
                - name: DATABASE_NAME
                  value: homebox
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      name: homebox-postgres
                      key: username
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: homebox-postgres
                      key: password
              volumeMounts:
                - name: backup-volume
                  mountPath: /backups
                - name: script
                  mountPath: /scripts
          volumes:
            - name: backup-volume
              hostPath:
                # this already exists on the host
                path: /custom/backup/backup
                type: Directory
            - name: script
              configMap:
                name: postgres-backup-script
                defaultMode: 0755
