---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: homebox
  namespace: homebox
# https://cloudnative-pg.io/documentation/1.28/cloudnative-pg.v1/#postgresql-cnpg-io-v1-ClusterSpec
spec:
  instances: 1
  # https://github.com/cloudnative-pg/postgres-containers
  imageName: ghcr.io/cloudnative-pg/postgresql:17.7-minimal-trixie
 
  storage:
    size: 1Gi
    storageClass: local-path-customized
 
  postgresql:

  bootstrap:
    initdb:
      database: homebox
      owner: homebox
      secret:
        name: homebox-postgres
