---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: homebox-postgres
  namespace: homebox
# https://cloudnative-pg.io/documentation/1.28/cloudnative-pg.v1/#postgresql-cnpg-io-v1-ClusterSpec
spec:
  instances: 1
  # https://github.com/cloudnative-pg/postgres-containers
  imageName: ghcr.io/cloudnative-pg/postgresql:17.9-minimal-trixie@sha256:785ce76bd65381e07e9c3f7018dd2295c83756f06c0d9ab1c97a4e91d379eeb6
  storage:
    size: 1Gi
    storageClass: local-path-customized
  postgresql:
  bootstrap:
    initdb:
      database: homebox
      owner: homebox
      secret:
        name: homebox-postgres
