---
name: yamllint

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "0 5 * * 0"
  workflow_dispatch:

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Run yamllint
        run: |
          python3 --version
          pip3 install --user yamllint
          yamllint --version
          yamllint .
